### ISSUE TITLE
Mapping of variables should be defined & saved bi-directionally as default

### ISSUE THREAD

**Issue by stepjah** [RHEAGROUP/DEH-ECOSIMPRO#64] opened 2021-03-30 06:53 UTC
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the DEHP-EcosimPro
- [x] I have searched [open](https://github.com/RHEAGROUP/DEHP-ECOSIMPRO/issues) and [closed](https://github.com/RHEAGROUP/DEHP-ECOSIMPRO/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Currently, the mapping of data between the DST and the Hub are saved individually. To map the same parameter for the transfer in both directions, two individual mappings have to be created in the respective dialogues. To reduce the effort, the standard way to create a mapping should be bi-directional (DST<-->Hub) for most of the use cases. To give the user still the flexibility to do other-ways, a respective check-box could be foreseen to specify the wish to create a one-directional mapping. 
The result shall be saved in the mapping configuration for later re-use.

### System Configuration

- DEH-ECOSIM version: 1.3.1
- Environment (Operating system, version and so on): WIN10, 64bit
- .NET Framework version:
- Additional information:

**Comment by alexatrhea** [comment] 2021-04-20 09:38
Might be duplicate of #72

**Closed** 2021-11-14 12:58 UTC
Labels: DEH-ECOSIM, 1sp, medium
